# Generated by Django 4.1.13 on 2024-09-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_alter_household_admin'),
        ('pantryManagement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantry',
            name='household',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pantry', to='userManagement.household'),
        ),
    ]
