# Generated by Django 4.1.13 on 2024-09-15 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManagement', '0002_remove_recipe_ingredients_alter_recipe_ratings_and_more'),
        ('pantryManagement', '0003_alter_pantry_household'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantry',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='PantryIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeManagement.ingredient')),
                ('pantry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantryManagement.pantry')),
            ],
            options={
                'unique_together': {('pantry', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='pantry',
            name='ingredients',
            field=models.ManyToManyField(through='pantryManagement.PantryIngredient', to='recipeManagement.ingredient'),
        ),
    ]
