# Generated by Django 4.1.13 on 2024-09-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManagement', '0002_remove_recipe_ingredients_alter_recipe_ratings_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userManagement', '0002_alter_household_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='my_recipes',
        ),
        migrations.AddField(
            model_name='household',
            name='saved_recipes',
            field=models.ManyToManyField(related_name='saved_by_households', to='recipeManagement.recipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_management_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_management_user_permissions_set', to='auth.permission'),
        ),
    ]
