# Generated by Django 4.1.13 on 2024-09-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_management', '0005_alter_recipeingredient_unit'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='recently_added',
            field=models.ManyToManyField(related_name='recently_added_by_households', to='recipe_management.recipe'),
        ),
    ]
