# Generated by Django 5.1.1 on 2024-09-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_management', '0005_alter_recipeingredient_unit'),
        ('user_management', '0002_household_recently_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='recently_added',
            field=models.ManyToManyField(related_name='receadntly_added_by_households', to='recipe_management.recipe'),
        ),
    ]
