# Generated by Django 5.1.1 on 2024-10-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_management', '0005_alter_recipeingredient_unit'),
        ('user_management', '0003_alter_household_recently_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='recipe_management.recipe'),
        ),
    ]
