# Generated by Django 5.1.1 on 2024-10-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_user_saved_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='join_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
