# Generated by Django 5.1.1 on 2024-11-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_auto_20241107_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='join_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
