# Generated by Django 5.1.1 on 2024-09-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_management', '0004_category_recipe_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
