# Generated by Django 5.1.1 on 2024-10-13 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe_management', '0005_alter_recipeingredient_unit'),
        ('user_management', '0003_alter_household_recently_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_list', to='user_management.household')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='grocery_lists', to='recipe_management.ingredient')),
            ],
        ),
    ]
