const CategoryLists = {
    "Cuisine Types": {
      subcategories: {
        American: [
          "Apple Pie",
          "Baked Beans",
          "Bagels",
          "Banana Breads",
          "Beef Stews",
          "Biscuits",
          "Blueberry Pie",
          "Buffalo Chicken Wings",
          "Cornbread",
          "Fried Chicken",
          "Macaroni and Cheese",
          "Meatloaf",
        ],
        Asian: [
          "Beef Stroganoff",
          "Beef Tenderloin",
          "Bulgogi",
          "Chicken Adobo",
          "Chicken Teriyaki",
          "Chinese",
          "Egg Rolls",
          "Etouffee",
          "Pad Thai",
          "Noodles",
          "Sushi",
          "Shrimp Scampi",
        ],
        Mexican: [
          "Burritos",
          "Enchiladas",
          "Fajitas",
          "Guacamole",
          "Chiles Rellenos",
          "Nachos",
          "Quesadillas",
          "Salsa",
          "Tamales",
          "Tacos",
          "Taco Salads",
          "Mexican",
        ],
        European: [
          "Bruschetta",
          "Chicken Marsala",
          "Goulash",
          "Minestrone Soups",
          "Paella",
          "Pierogies",
          "Shepherd's Pie",
          "French Onion Soups",
          "Borscht",
          "Kolache",
          "Calzones",
          "Pasta Primavera",
        ],
        Mediterranean: [
          "Falafel",
          "Greek",
          "Hummus",
          "Gyros",
          "Pita",
          "Shawarma",
          "Greek Salad",
          "Baba Ghanoush",
          "Tabouli",
          "Ceviche",
          "Paella",
          "Couscous",
        ],
        Indian: [
          "Chicken Curry",
          "Chicken Marsala",
          "Biryani",
          "Naan",
          "Lentil Soups",
          "Butter Chicken",
          "Aloo Gobi",
          "Tikka Masala",
          "Chutney",
          "Paneer",
          "Samosas",
          "Indian",
        ],
      },
    },
    "Meal Types": {
      subcategories: {
        Breakfast: [
          "Bagels",
          "Breakfast Burritos",
          "Breakfast Casseroles",
          "French Toast",
          "Omelets",
          "Pancakes",
          "Waffles",
          "Muffins",
          "Frittatas",
          "Smoothies",
          "Eggs Benedict",
          "Overnight Oats",
        ],
        Lunch: [
          "Burritos",
          "Calzones",
          "Chicken Salads",
          "Enchiladas",
          "Macaroni and Cheese",
          "Quesadillas",
          "Sandwiches",
          "Sliders",
          "Taco Salads",
          "Panini",
          "Burgers",
          "Wraps",
        ],
        Dinner: [
          "Beef Stroganoff",
          "Beef Stews",
          "Chicken Cordon Bleu",
          "Chicken Parmesan",
          "Chicken Piccata",
          "Chicken and Dumplings",
          "Lamb",
          "Lasagna",
          "Pot Roast",
          "Meatloaf",
          "Pork Tenderloin",
          "Ravioli",
        ],
        Desserts: [
          "Angel Food Cakes",
          "Apple Pie",
          "Banana Breads",
          "Biscotti",
          "Blondies",
          "Brownies",
          "Cakes",
          "Cherry Pie",
          "Cheesecakes",
          "Cookies",
          "Cupcakes",
          "Fudge",
        ],
        Appetizers: [
          "Artichoke Dips",
          "Buffalo Chicken Dips",
          "Cheese Balls",
          "Bruschetta",
          "Crackers",
          "Deviled Eggs",
          "Nachos",
          "Stuffed Mushrooms",
          "Spinach Dips",
          "Falafel",
          "Hummus",
          "Tapas",
        ],
      },
    },
    "Holiday & Seasonal": {
      subcategories: {
        Christmas: [
          "Christmas Cookies",
          "Eggnog",
          "Divinity",
          "Cranberry Sauces",
          "Fruitcakes",
          "Gingerbread Cookies",
          "Chocolate Fudge",
          "Hot Chocolate",
          "Mulled Wine",
          "Pumpkin Pie",
          "Stuffing",
          "Yule Log",
        ],
        Thanksgiving: [
          "Turkey",
          "Gravy",
          "Cranberry Sauces",
          "Green Bean Casseroles",
          "Pumpkin Pie",
          "Mashed Potatoes",
          "Cornbread",
          "Pecan Pie",
          "Apple Pie",
          "Stuffing",
          "Sweet Potato Pie",
          "Rolls",
        ],
        Easter: [
          "Deviled Eggs",
          "Hot Cross Buns",
          "Lamb",
          "Carrot Cakes",
          "Easter Bread",
          "Quiches",
          "Scones",
          "Easter Desserts",
          "Glazed Ham",
          "Scalloped Potatoes",
          "Asparagus",
          "Eggs Benedict",
        ],
        "Fourth of July": [
          "BBQ",
          "Burgers",
          "Hot Dogs",
          "Potato Salads",
          "Coleslaws",
          "Corn on the Cob",
          "Lemonade",
          "Fried Chicken",
          "Ribs",
          "Cornbread",
          "Watermelon Salad",
          "Ice Cream",
        ],
        Halloween: [
          "Candy Apples",
          "Halloween Cookies",
          "Pumpkin Seeds",
          "Punch",
          "Caramel Apples",
          "Popcorn Balls",
          "Witches' Fingers",
          "Ghost Brownies",
          "Spooky Jell-O Shots",
          "Cupcakes",
          "Spider Cookies",
          "Pretzels",
        ],
        "Mother's Day": [
          "Muffins",
          "French Toast",
          "Quiches",
          "Mimosas",
          "Frittatas",
          "Pancakes",
          "Fruit Salads",
          "Waffles",
          "Breakfast Casseroles",
          "Scones",
          "Croissants",
          "Crepes",
        ],
        "Father's Day": [
          "Steaks",
          "Burgers",
          "Buffalo Wings",
          "BBQ Ribs",
          "Potato Salads",
          "Grilled Chicken",
          "Corn on the Cob",
          "Fried Chicken",
          "Pulled Pork",
          "Cornbread",
          "Coleslaws",
          "Deviled Eggs",
        ],
      },
    },
    "Cooking Methods": {
      subcategories: {
        Baking: [
          "Bagels",
          "Biscuits",
          "Breads",
          "Cakes",
          "Cookies",
          "Brownies",
          "Muffins",
          "Cupcakes",
          "Pizza Dough",
          "Pies",
          "Scones",
          "Pretzels",
        ],
        Grilling: [
          "Burgers",
          "Hot Dogs",
          "Ribs",
          "Grilled Chicken",
          "Grilled Vegetables",
          "BBQ",
          "Pork Chops",
          "Steaks",
          "Lamb",
          "Grilled Shrimp",
          "Grilled Salmon",
          "Grilled Pineapple",
        ],
        "Air Fryer": [
          "Air Fryer Recipes",
          "Air Fryer Vegetables",
          "Air Fryer Fish",
          "Air Fryer Fries",
          "Air Fryer Wings",
          "Air Fryer Donuts",
          "Buffalo Chicken Wings",
          "Fried Chicken",
          "Sweet Potato Fries",
          "Air Fryer Tofu",
          "Popcorn",
          "Egg Rolls",
        ],
        "Slow Cooker": [
          "Slow Cooker Recipes",
          "Beef Stews",
          "Chili Recipes",
          "Pulled Pork",
          "Pot Roast",
          "Chicken and Dumplings",
          "Soups",
          "Casseroles",
          "Meatballs",
          "Beef Stroganoff",
          "Ribs",
          "Chicken Noodle Soups",
        ],
        "Instant Pot": [
          "Instant Pot Recipes",
          "Soups",
          "Beef Stews",
          "Chili Recipes",
          "Casseroles",
          "Risotto",
          "Beans",
          "Chicken and Dumplings",
          "Pulled Pork",
          "Pot Roast",
          "Yogurt",
          "Pasta Dishes",
        ],
        "Sous Vide": [
          "Sous Vide Recipes",
          "Steaks",
          "Chicken Breasts",
          "Salmon",
          "Vegetables",
          "Eggs",
          "Pork Tenderloin",
          "Lamb",
          "Duck",
          "Shrimp",
          "Custards",
          "Turkey Breast",
        ],
      },
    },
    "Dietary Preferences": {
      subcategories: {
        Vegan: [
          "Falafel",
          "Hummus",
          "Vegan",
          "Vegan Pizza",
          "Quinoa",
          "Smoothies",
          "Tofu",
          "Seitan",
          "Lentil Soups",
          "Stuffed Mushrooms",
          "Grilled Vegetables",
          "Guacamole",
        ],
        Vegetarian: [
          "Eggplant Parmesan",
          "Spinach Dips",
          "Stuffed Mushrooms",
          "Pasta Primavera",
          "Cheese Fondue",
          "Omelets",
          "Mushroom Soups",
          "Zucchini Breads",
          "Macaroni and Cheese",
          "Grilled Vegetables",
          "Vegetarian Tacos",
          "Falafel",
        ],
        "Gluten-Free": [
          "Gluten-Free",
          "Gluten-Free Cookies",
          "Oatmeal",
          "Rice Pilaf",
          "Risotto",
          "Quinoa",
          "Frittatas",
          "Grilled Vegetables",
          "Smoothies",
          "Chicken Salads",
          "Chocolate Fudge",
          "Fruit Salads",
        ],
        Keto: [
          "Keto",
          "Low Carb",
          "Zucchini Noodles",
          "Steak",
          "Grilled Chicken",
          "Bacon",
          "Eggs",
          "Avocado Salad",
          "Chicken Salad",
          "Tofu",
          "Cauliflower Rice",
          "Omelets",
        ],
        "Low-Calorie": [
          "Low Calorie",
          "Low Fat",
          "Low Cholesterol",
          "Low Sodium",
          "Smoothies",
          "Chicken Salads",
          "Green Salads",
          "Grilled Chicken",
          "Stir-Fries",
          "Steamed Vegetables",
          "Quinoa",
          "Oatmeal",
        ],
      },
    },
    Ingredients: {
      subcategories: {
        "Meat & Poultry": [
          "Beef Recipes",
          "Chicken Recipes",
          "Pork",
          "Lamb",
          "Ground Beef",
          "Turkey",
          "Chicken Wings",
          "Chicken Thighs",
          "Pork Tenderloin",
          "Sausage",
          "Meatballs",
          "Ribs",
        ],
        Seafood: [
          "Shrimp",
          "Salmon",
          "Crab Cakes",
          "Ceviche",
          "Tuna Casseroles",
          "Fish",
          "Clams",
          "Lobster",
          "Scallops",
          "Shrimp Scampi",
          "Sushi",
          "Seafood Chowders",
        ],
        Vegetables: [
          "Broccoli Salads",
          "Zucchini Breads",
          "Eggplant Parmesan",
          "Green Salads",
          "Potato Salads",
          "Sweet Potatoes",
          "Mushrooms",
          "Butternut Squash Soups",
          "Spinach Dips",
          "Carrot Cakes",
          "Guacamole",
          "Tomatoes",
        ],
        Fruits: [
          "Apple Pie",
          "Applesauce",
          "Bananas",
          "Blueberry Pie",
          "Strawberry Shortcakes",
          "Cherry Pie",
          "Lemon Bars",
          "Rhubarb Pie",
          "Cranberry Sauces",
          "Mangoes",
          "Peaches",
          "Fruit Salads",
        ],
        "Dairy & Eggs": [
          "Cheesecakes",
          "Egg Salads",
          "Omelets",
          "Frittatas",
          "Creme Brulee",
          "Ice Cream",
          "Cheese Balls",
          "Cheese Fondue",
          "Ricotta",
          "Parmesan",
          "Yogurt",
          "Eggs Benedict",
        ],
        "Grains & Bread": [
          "Bagels",
          "Breads",
          "Biscuits",
          "Cornbread",
          "Muffins",
          "Flatbreads",
          "English Muffins",
          "Pizza Dough",
          "Pasta Dishes",
          "Oatmeal",
          "Crackers",
          "Pretzels",
          "Pancakes",
        ],
        "Spices & Sauces": [
          "Barbecue Sauce",
          "Gravy",
          "Marinades",
          "Relishes",
          "Salsa",
          "Salad Dressings",
          "Pesto",
          "Brines",
          "Hot Sauce",
          "Cheese Fondue",
          "Fondant",
          "Garlic Butter",
        ],
      },
    },
  };

export default CategoryLists;