# Generated by Django 4.1.13 on 2024-09-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManagement', '0002_remove_recipe_ingredients_alter_recipe_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
