# Generated by Django 4.1.13 on 2024-09-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planning', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplanrecipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('snack', 'Snack')], max_length=10, null=True),
        ),
    ]
