# Generated by Django 5.1.1 on 2024-09-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planning', '0004_mealplanrecipe_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplanrecipe',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=15, null=True),
        ),
    ]
