# Generated by Django 4.1.13 on 2024-09-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManagement', '0001_initial'),
        ('mealPlanning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.user'),
        ),
    ]
