# Generated by Django 4.1.13 on 2024-09-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_alter_household_admin'),
        ('mealPlanning', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userManagement.user'),
        ),
    ]
