# Generated by Django 4.1.13 on 2024-09-15 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManagement', '0002_remove_recipe_ingredients_alter_recipe_ratings_and_more'),
        ('userManagement', '0002_alter_household_admin'),
        ('mealPlanning', '0003_alter_mealplan_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='plan',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='household',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_plans', to='userManagement.household'),
        ),
        migrations.CreateModel(
            name='MealPlanRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealPlanning.mealplan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeManagement.recipe')),
            ],
            options={
                'unique_together': {('meal_plan', 'recipe', 'day')},
            },
        ),
        migrations.AddField(
            model_name='mealplan',
            name='recipes',
            field=models.ManyToManyField(through='mealPlanning.MealPlanRecipe', to='recipeManagement.recipe'),
        ),
    ]
